fiftytwodays/reporting-hub

- app/shared/ui/core/ui/Layout.tsx
fix: removed department from the menu
> fix: removed department from the menu

- amplify/data/resource.ts
- app/settings/functional-area/page.tsx
feat(functional-area): Implement functional area
> feat(functional-area): Implement functional area

- package-lock.json
- package.json
- src/app/layout.tsx
- src/app/login/page.tsx
- src/app/page.tsx
- src/shared/ui/core/ui/Layout.tsx
- src/shared/ui/core/ui/Login.tsx
1. Ensure a profile avatar is displayed at the top-right corner of the navigation bar.
2. If the user is not logged in, display "Sign In" text; if logged in, display the username.
3. On logout, redirect the page to the login route.
> feat(layout): add user profile icon and authentication flow

- package-lock.json
- package.json
> core: add eslint as dev dependency

- src/shared/ui/page/ui/Page.tsx
> fix(Layout): add type definitions for Page component

- src/app/settings/project-type/page.tsx
- src/entities/project-type/api/project-types-list.ts
- src/entities/project-type/config/columns.ts
- src/entities/project-type/config/types.ts
- src/entities/project-type/index.ts
- src/entities/project-type/lib/generate-columns.tsx
- src/entities/project-type/ui/ProjectTypesList.tsx
- src/feature/create-project-type/api/create-project-type.ts
- src/feature/create-project-type/index.ts
- src/feature/create-project-type/ui/CreateProjectTypeForm.tsx
- src/feature/create-project-type/ui/CreateProjectTypeModal.tsx
- src/feature/delete-project-type/delete-project-type.ts
- src/feature/edit-project-type/api/edit-project-type.ts
- src/feature/edit-project-type/index.ts
- src/feature/edit-project-type/ui/EditProjectTypeForm.tsx
- src/feature/edit-project-type/ui/EditProjectTypeModal.tsx
- src/widgets/project-types-list/index.ts
- src/widgets/project-types-list/ui/ProjectTypesList.tsx
> feat(project-type): Convert to FSD strucutre and use EntityList. Update forms

- src/entities/cluster/lib/generate-columns.tsx
- src/entities/cluster/ui/ClustersList.tsx
- src/entities/functional-area/lib/generate-columns.tsx
- src/entities/functional-area/ui/FunctionalAreasList.tsx
- src/entities/project-type/lib/generate-columns.tsx
- src/entities/project-type/ui/ProjectTypesList.tsx
- src/entities/project/lib/generate-columns.tsx
- src/entities/project/ui/ProjectsList.tsx
- src/entities/region/lib/generate-columns.tsx
- src/entities/region/ui/RegionsList.tsx
- src/shared/ui/entity-list/config/types.ts
- src/shared/ui/entity-list/ui/EntityList.tsx
> fix(core): fix type issues in entities

- src/app/settings/organization/page.tsx
- src/feature/edit-organization/ui/EditButton.tsx
- src/widgets/organizations-list/ui/OrganizationsList.tsx
…whether object is tehre or not
> fix(organization): Update the condition to check for name instead of whether object is tehre or not

- src/app/yearly-form/approver-view/[id]/page.tsx
- src/app/yearly-form/my-forms/[id]/page.tsx
- src/app/yearly-form/my-forms/page.tsx
- src/app/yearly-form/reviewer-view/[id]/page.tsx
- src/entities/yearly-form/api/quarterlyplan-list.ts
- src/entities/yearly-form/api/yearlyplan-details.ts
- src/entities/yearly-form/api/yearlyplan-full.ts
- src/entities/yearly-form/api/yearlyplan-list.ts
- src/entities/yearly-form/lib/generate-columns.tsx
- src/feature/create-monthly-form/ui/CreateMonthlyFormForm.tsx
- src/feature/create-yearly-form/api/create-plan.ts
- src/feature/create-yearly-form/api/create-yearly-form.ts
- src/feature/create-yearly-form/api/update-plan.ts
- src/feature/create-yearly-form/ui/CreateYearlyFormNew.tsx
- src/feature/create-yearly-form/ui/FunctionalArea.tsx
- src/feature/create-yearly-form/ui/Projects.tsx
- src/feature/create-yearly-form/ui/QuarterlyPlan.tsx
- src/feature/delete-plan/delete-plan.ts
- src/shared/ui/core/ui/Layout.tsx
- src/widgets/myforms-list/ui/MyFormsList.tsx
> fix(8-15): fix for issues and avoided unwanted logging

- src/shared/ui/core/ui/Layout.tsx
> feature(hidesignup): Avoided option to signup in the login page

- amplify/data/resource.ts
- src/app/yearly-form/approver-view/[id]/page.tsx
- src/app/yearly-form/my-forms/[id]/page.tsx
- src/app/yearly-form/my-forms/page.tsx
- src/entities/yearly-form/api/yearlyplan-list.ts
- src/entities/yearly-form/lib/generate-columns.tsx
- src/entities/yearly-form/ui/YearlyPlansList.tsx
- src/feature/create-yearly-form/ui/CreateYearlyFormNew.tsx
- src/feature/create-yearly-form/ui/Projects.tsx
- src/shared/ui/comment/CommentModal.tsx
- src/widgets/myforms-list/ui/MyFormsList.tsx
> fix(issues-fix-125): fix for issues 15 - 25

- amplify/data/resource.ts
- src/app/yearly-form/approver-view/[id]/page.tsx
- src/app/yearly-form/my-forms/[id]/page.tsx
- src/app/yearly-form/my-forms/page.tsx
- src/entities/yearly-form/api/yearlyplan-list.ts
- src/entities/yearly-form/config/types.ts
- src/entities/yearly-form/lib/generate-columns.tsx
- src/entities/yearly-form/ui/YearlyPlansList.tsx
- src/feature/create-yearly-form/ui/CreateYearlyFormNew.tsx
- src/feature/create-yearly-form/ui/Projects.tsx
- src/shared/ui/comment/CommentModal.tsx
- src/widgets/myforms-list/ui/MyFormsList.tsx
125 fix uat prod critical issues
> 125 fix uat prod critical issues

- amplify/data/resource.ts
- src/entities/yearly-form/api/yearlyplan-full.ts
> fix(issues-in-listing-plans): Added secondary Index in model

- amplify/data/resource.ts
- src/entities/yearly-form/api/yearlyplan-full.ts
> fix(issuesin -listing-quarter-plans): added secondary index

- src/app/yearly-form/approver-view/[id]/view/page.tsx
- src/app/yearly-form/my-forms/[id]/view/page.tsx
- src/app/yearly-form/reviewer-view/[id]/view/page.tsx
- src/entities/yearly-form/lib/generate-columns.tsx
- src/entities/yearly-form/ui/YearlyPlansList.tsx
- src/feature/create-yearly-form/ui/CreateYearlyFormNew.tsx
- src/widgets/myforms-list/ui/MyFormsList.tsx
> Added view option

- src/feature/create-yearly-form/ui/CreateYearlyFormNew.tsx
> Disabled delete plan button

- src/entities/monthly-form/api/get-monthlyForms.ts
- src/entities/parameters/api/parameters-list.ts
- src/feature/create-monthly-form/ui/CreateMonthlyFormForm.tsx
> fix(): Form rerendering issue fix and update the facilitator Id to use userId if monthly form is not there

- src/feature/create-monthly-form/ui/CreateMonthlyFormForm.tsx
- src/widgets/monthly-forms-list-approver/ui/MonthlyFormsListApprover.tsx
> fix(approver-view): Add condition for getting monthly forms and add condition to fetch all projects when action is approver-view

- src/entities/reporting-status-reports/api/fetch-utils.ts
> fix(): Removed facilitatorId and used userId since both holds the same value

- src/entities/monthly-form -approver/api/get-monthlyForm-user.ts
- src/entities/monthly-form -approver/api/get-specific-monthlyForm.ts
- src/entities/monthly-form/api/get-monthlyForm-user.ts
- src/entities/monthly-form/api/get-specific-monthlyForm.ts
> feat(monthly-form-listing): implementing sorting so that latest forms will be at the top
